#!/bin/bash

while read -r file
do
    case "$1" in
    "g")
        tr '\n' '\0' | xargs -0 gimp ;;
    "n")
        echo -n "$file" | xclip -selection clipboard ;;
    "d")
        echo -n "$PWD" | xclip -selection clipboard;;
    "p")
        echo -n "$PWD"/"$file" | xclip -selection clipboard ;;
    "i")
        xclip -selection clipboard -target image/png "$file" ;;
    esac
done
