#!/bin/bash

while read -r file
do
    case "$1" in
    "D")
        mv "$file" ~/.trash ;;
    "g")
        tr '\n' '\0' | xargs -0 gimp ;;
    "n")
        echo -n "$file" | xclip -selection clipboard ;;
    "e")
        st -e sh -c "exiftool '$file' | less" ;;
    "d")
        echo -n "$PWD" | xclip -selection clipboard;;
    "p")
        echo -n "$PWD"/"$file" | xclip -selection clipboard ;;
    "i")
        xclip -selection clipboard -target image/png "$file" ;;
    "f")
        nitrogen --set-auto "$file" ;;
    esac
done
