env:
  TERM: xterm-256color

window:
  opacity: 1
  dimensions:
    columns: 1440
    lines: 81
  padding:
    x: 0
    y: 0
  dynamic_padding: true
  decorations: full
  startup_mode: Windowed
scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Hack
  bold:
    family: Hack
  italic:
    family: Hack
  size: 14
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

colors:
  primary:
    background: "0x000000"
    foreground: "0xebdbb2"
  cursor:
    text: "0x000000"
    cursor: "0xebdbb2"
  normal:
    black: "0x000000"
    red: "0xfb4934"
    green: "0xb8bb26"
    yellow: "0xfabd2f"
    blue: "0x83a598"
    magenta: "0xb16286"
    cyan: "0x689d6a"
    white: "0xebdbb2"
  bright:
    black: "0x928374"
    red: "0xfb4934"
    green: "0xb8bb26"
    yellow: "0xfabd2f"
    blue: "0x83a598"
    magenta: "0xd3869b"
    cyan: "0x8ec07c"
    white: "0xffffff"
