env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 0
    lines: 0
  padding:
    x: 0
    y: 0
  dynamic_padding: false
  decorations: full
  startup_mode: Windowed
scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Hack
  bold:
    family: Hack
  italic:
    family: Hack

  size: 14.5
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  use_thin_strokes: true

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '0x000000'
    foreground: '0xebdbb2'
  normal:
    black:   '0x000000'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83A598'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0xebdbb2'
  bright:
    black:   '0x928374'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'

background_opacity: 1

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true
  hints:
    modifiers: None
selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: false
window.dynamic_title: true

cursor:
  style: Block
  unfocused_hollow: false

live_config_reload: true

working_directory: None

enable_experimental_conpty_backend: false

alt_send_esc: false
key_bindings:
  # (Windows/Linux only)
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
