distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 0.2.3
install_time: "Wed Apr  6 00:29:44 2022"
installation_id: "10beaa6c-2c0b-47e7-8f24-64a527eb6e17"
rime_version: 1.7.3